service: hello-world

plugins:
  # - serverless-microstrate
  # during dev
  - ../

package:
  individually: true

custom:
  apiPrefix: apiv2

provider:
  name: microstrate
  region: eu-west-2
  runtime: nodejs20.x
  architecture: arm64
  stage: prod
  memorySize: 1024 # default is 1024
  timeout: 60
  environment:
    SERVICE: ${self:service}

resources:
  Description: ${self:service} service stack
  Resources:
    DataStore:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        Description: Table for storing records
        TableName: DataStore
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH

    DataBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        Description: Bucket for storing files
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        BucketName: DataBucket
        Tags:
          - Key: a
            Value: b
          - Key: c
            Value: d
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - POST
                - GET
              ExposedHeaders:
                - x-amz-server-side-encryption
                - x-amz-request-id
                - x-amz-id-2
              MaxAge: 3000

functions:
  hello:
    handler: handler.hello
    description: hello world desc
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: ${self:custom.apiPrefix}/hello
          method: 'post'
          cors:
            origins:
              - '*'
