service: hello-world

plugins:
  # - serverless-microstrate
  # during dev
  - ../

package:
  individually: true

custom:
  apiPrefix: apiv2

provider:
  name: microstrate
  region: eu-west-2
  runtime: nodejs20.x
  architecture: arm64
  stage: prod
  memorySize: 1024
  timeout: 60
  environment:
    SERVICE: ${self:service}

resources:
  Description: ${self:service} service stack
  Resources:
    DataStore:
      type: microstrate::kv::bucket
      deletion_policy: retain
      properties:
        bucket: DataStore
        description: Table for storing records
        indexing:
          mappings:
            - field: PK
              field_type: text
            - field: SK
              field_type: text
            - field: subject
              field_type: text
            - field: topic
              field_type: tex

    DataBucket:
      type: microstrate::objectstore::bucket
      deletion_policy: retain
      properties:
        bucket: DataBucket
        description: Bucket for storing files
        metadata:
          a: b
          c: d

    DataStream:
      type: microstrate::stream
      deletion_policy: retain
      properties:
        name: DataStream
        description: stream for storing events
        subjects:
          - ONE.>
          - TWO.>
        max_consumers: 10
        max_msgs: 1000
        storage: file
        discard_new_per_subject: false
        max_msgs_per_subject: 100
        max_msg_size: 1024
        num_replicas: 2
        metadata:
          a: b
          c: d

    DataGateway:
      type: microstrate::gateway
      deletion_policy: retain
      properties:
        name: DataGateway
        description: gateway for serving events
        active: true
        limit:
          request: 100
          time: 100
        metadata:
          a: b
          c: d

functions:
  hello:
    handler: handler.hello
    description: hello desc
    memorySize: 128
    timeout: 3
    environment:
      APP_ENV_VARIABLE: FOOBAR
    gateway:
      - path: ${self:custom.apiPrefix}/hello
        is_public: true
        limit:
          request: 100
          time: 1000
        method: post
        timeout: 120

  world:
    handler: handler.hello
    description: world desc
    tags:
      foo: bar

  helloWorld:
    handler: handler.hello
    gateway:
      - path: ${self:custom.apiPrefix}/hello
        method: post
      # - path: ${self:custom.apiPrefix}/hello
      #   method: put
      # - path: ${self:custom.apiPrefix}/hello
      #   method: get
      # - path: ${self:custom.apiPrefix}/hello
      #   method: delete
